# 02 - Data Profiling

## Objective

This notebook examines the structure and quality of the raw flight dataset before data cleaning and descriptive analytics.

The profiling process includes:

- Reviewing dataset dimensions and schema
- Measuring missing values
- Identifying duplicate records
- Summarizing numerical variables
- Reviewing key categorical variables
- Performing essential data-quality checks

The findings from this notebook will guide the data-cleaning and descriptive-analytics decisions.

#### Load configuration and dataset

In [1]:
import importlib.util
import os
from pathlib import Path

_bootstrap = Path.cwd() / "notebooks" / "import_path.py"
if not _bootstrap.is_file():
    _bootstrap = Path.cwd() / "import_path.py"
_spec = importlib.util.spec_from_file_location("import_path", _bootstrap)
_ip = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_ip)

# Load the project configuration and raw flight table

from config import project_config as cfg
from dotenv import dotenv_values
from pyspark.sql import functions as F
from pyspark.sql.types import NumericType

DATABRICKS_PROFILE = os.getenv(
    "DATABRICKS_CONFIG_PROFILE", "capstone-serverless"
)
api_env_candidates = [
    Path.cwd() / "api" / ".env",
    Path.cwd().parent / "api" / ".env",
]
api_env_path = next(
    (candidate for candidate in api_env_candidates if candidate.is_file()),
    None,
)
api_credentials = dotenv_values(api_env_path) if api_env_path else {}
LOCAL_DATABRICKS_HOST = str(
    api_credentials.get("DATABRICKS_SERVER_HOSTNAME", "")
).strip()
LOCAL_DATABRICKS_TOKEN = str(
    api_credentials.get("DATABRICKS_ACCESS_TOKEN", "")
).strip()
if LOCAL_DATABRICKS_HOST and not LOCAL_DATABRICKS_HOST.startswith("http"):
    LOCAL_DATABRICKS_HOST = f"https://{LOCAL_DATABRICKS_HOST}"

try:
    spark
except NameError:
    from databricks.connect import DatabricksSession

    builder = DatabricksSession.builder.serverless()
    if LOCAL_DATABRICKS_HOST and LOCAL_DATABRICKS_TOKEN:
        builder = builder.host(LOCAL_DATABRICKS_HOST).token(
            LOCAL_DATABRICKS_TOKEN
        )
    else:
        builder = builder.profile(DATABRICKS_PROFILE)
    spark = builder.getOrCreate()

if not spark.catalog.tableExists(cfg.RAW_TABLE):
    raise RuntimeError(
        f"Required table '{cfg.RAW_TABLE}' was not found. "
        "Run Notebook 01 before continuing."
    )

df_raw = spark.read.table(cfg.RAW_TABLE)

print(f"Table loaded: {cfg.RAW_TABLE}")

Table loaded: workspace.default.flights_raw

#### Dataset overview

This section reviews the size and structure of the raw flight dataset.

In [2]:
# Review dataset dimensions

row_count = df_raw.count()
column_count = len(df_raw.columns)

print(f"Total records: {row_count:,}")
print(f"Total columns: {column_count}")

Total records: 7,001,619
Total columns: 32

In [3]:
# Review the inferred schema

df_raw.printSchema()

root
 |-- QUARTER: integer (nullable = true)
 |-- MONTH: integer (nullable = true)
 |-- DAY_OF_WEEK: integer (nullable = true)
 |-- FL_DATE: string (nullable = true)
 |-- OP_UNIQUE_CARRIER: string (nullable = true)
 |-- OP_CARRIER_FL_NUM: integer (nullable = true)
 |-- ORIGIN: string (nullable = true)
 |-- ORIGIN_CITY_NAME: string (nullable = true)
 |-- ORIGIN_STATE_NM: string (nullable = true)
 |-- DEST: string (nullable = true)
 |-- DEST_CITY_NAME: string (nullable = true)
 |-- DEST_STATE_NM: string (nullable = true)
 |-- CRS_DEP_TIME: integer (nullable = true)
 |-- DEP_DELAY: double (nullable = true)
 |-- DEP_DEL15: double (nullable = true)
 |-- TAXI_OUT: double (nullable = true)
 |-- TAXI_IN: double (nullable = true)
 |-- CRS_ARR_TIME: integer (nullable = true)
 |-- ARR_DELAY: double (nullable = true)
 |-- ARR_DEL15: double (nullable = true)
 |-- CANCELLED: double (nullable = true)
 |-- CANCELLATION_CODE: string (nullable = true)
 |-- DIVERTED: double (nullable = true)
 |-- CRS_ELAPSED_TIME: double (nullable = true)
 |-- ACTUAL_ELAPSED_TIME: double (nullable = true)
 |-- AIR_TIME: double (nullable = true)
 |-- DISTANCE: double (nullable = true)
 |-- CARRIER_DELAY: double (nullable = true)
 |-- WEATHER_DELAY: double (nullable = true)
 |-- NAS_DELAY: double (nullable = true)
 |-- SECURITY_DELAY: double (nullable = true)
 |-- LATE_AIRCRAFT_DELAY: double (nullable = true)

#### Missing-value analysis

Missing values are measured for every column to identify variables that may require removal, imputation, or special treatment during data cleaning.

In [4]:
# Calculate missing-value counts for every column

null_counts = (
    df_raw
    .select(
        [
            F.sum(
                F.col(column_name).isNull().cast("long")
            ).alias(column_name)
            for column_name in df_raw.columns
        ]
    )
    .first()
)

missing_values_data = [
    (
        field.name,
        field.dataType.simpleString(),
        int(null_counts[field.name] or 0),
        round(
            (null_counts[field.name] or 0)
            / row_count
            * 100,
            2
        ),
    )
    for field in df_raw.schema.fields
]

missing_values_df = spark.createDataFrame(
    missing_values_data,
    [
        "column_name",
        "data_type",
        "null_count",
        "null_percentage",
    ],
)

display(
    missing_values_df.orderBy(
        F.col("null_percentage").desc(),
        F.col("column_name"),
    )
)

DataFrame[column_name: string, data_type: string, null_count: bigint, null_percentage: double]

In [5]:
# Focus on the columns that actually contain missing values

display(
    missing_values_df
    .filter(F.col("null_count") > 0)
    .orderBy(F.col("null_percentage").desc())
)

DataFrame[column_name: string, data_type: string, null_count: bigint, null_percentage: double]

#### Missing-value interpretation

The highest null percentages are expected in `CANCELLATION_CODE` and the five delay-cause columns (`CARRIER_DELAY`, `WEATHER_DELAY`, `NAS_DELAY`, `SECURITY_DELAY`, `LATE_AIRCRAFT_DELAY`), followed by post-departure fields such as `DEP_DELAY`, `DEP_DEL15`, `TAXI_OUT`, `TAXI_IN`, `ARR_DELAY`, `ARR_DEL15`, `ACTUAL_ELAPSED_TIME`, and `AIR_TIME`.

This pattern is structural, not a data-quality defect:

- `CANCELLATION_CODE` is only populated for cancelled flights, so it is null for the vast majority of records.
- The delay-cause columns are only populated for flights with a recorded delay, so they are null whenever a flight was on time, cancelled, or diverted.
- `DEP_DELAY`, `TAXI_OUT`, `TAXI_IN`, `ARR_DELAY`, `ACTUAL_ELAPSED_TIME`, and `AIR_TIME` are unavailable for cancelled flights, since those flights never departed or landed.

These nulls are investigated formally, and cross-checked against cancellation and diversion status, in `03_data_cleaning`. Any column showing nulls outside this expected pattern would need further investigation before proceeding.

#### Duplicate-record analysis

This section identifies fully duplicated rows that could distort flight counts and analytical results.

In [6]:
# Calculate fully duplicated records

distinct_record_count = df_raw.distinct().count()
duplicate_record_count = row_count - distinct_record_count

duplicate_percentage = round(
    duplicate_record_count / row_count * 100,
    4
)

print(f"Distinct records: {distinct_record_count:,}")
print(f"Duplicate records: {duplicate_record_count:,}")
print(f"Duplicate percentage: {duplicate_percentage}%")

Distinct records: 7,001,619
Duplicate records: 0
Duplicate percentage: 0.0%

In [7]:
# Calculate records sharing the same business key (potential duplicate flight events)

distinct_business_key_count = (
    df_raw
    .select(*cfg.BUSINESS_KEY_COLUMNS)
    .distinct()
    .count()
)
business_key_duplicate_count = (
    row_count - distinct_business_key_count
)

business_key_duplicate_percentage = round(
    business_key_duplicate_count / row_count * 100,
    4
)

print(f"Distinct business keys: {distinct_business_key_count:,}")
print(
    f"Records sharing a business key: "
    f"{business_key_duplicate_count:,}"
)
print(
    f"Business-key duplicate percentage: "
    f"{business_key_duplicate_percentage}%"
)

Distinct business keys: 7,001,619
Records sharing a business key: 0
Business-key duplicate percentage: 0.0%

#### Numerical summary

This section summarizes the distribution of numerical variables, including their central tendency, variation, ranges, and quartiles.

In [8]:
# Identify numerical columns

numeric_columns = [
    field.name
    for field in df_raw.schema.fields
    if isinstance(field.dataType, NumericType)
]

print(f"Numerical columns: {len(numeric_columns)}")

Numerical columns: 23

In [9]:
# Display descriptive statistics for numerical columns

display(
    df_raw
    .select(numeric_columns)
    .summary(
        "count",
        "mean",
        "stddev",
        "min",
        "25%",
        "50%",
        "75%",
        "max",
    )
)

DataFrame[summary: string, QUARTER: string, MONTH: string, DAY_OF_WEEK: string, OP_CARRIER_FL_NUM: string, CRS_DEP_TIME: string, DEP_DELAY: string, DEP_DEL15: string, TAXI_OUT: string, TAXI_IN: string, CRS_ARR_TIME: string, ARR_DELAY: string, ARR_DEL15: string, CANCELLED: string, DIVERTED: string, CRS_ELAPSED_TIME: string, ACTUAL_ELAPSED_TIME: string, AIR_TIME: string, DISTANCE: string, CARRIER_DELAY: string, WEATHER_DELAY: string, NAS_DELAY: string, SECURITY_DELAY: string, LATE_AIRCRAFT_DELAY: string]

#### Key categorical variables

This section reviews the cardinality and most frequent values of the main categorical variables used in the analysis.

In [10]:
# Keep only configured categorical columns available in the dataset

categorical_columns = [
    column_name
    for column_name in cfg.KEY_CATEGORICAL_COLUMNS
    if column_name in df_raw.columns
]

categorical_summary = []

for column_name in categorical_columns:
    distinct_count = (
        df_raw
        .select(column_name)
        .distinct()
        .count()
    )

    categorical_summary.append(
        (column_name, distinct_count)
    )

categorical_summary_df = spark.createDataFrame(
    categorical_summary,
    [
        "column_name",
        "distinct_value_count",
    ],
)

display(
    categorical_summary_df.orderBy(
        F.col("distinct_value_count").desc()
    )
)

DataFrame[column_name: string, distinct_value_count: bigint]

In [11]:
# Display the most frequent values for key categorical columns

for column_name in categorical_columns:
    print(f"Most frequent values for {column_name}:")

    display(
        df_raw
        .groupBy(column_name)
        .count()
        .orderBy(F.col("count").desc())
        .limit(cfg.TOP_N_RESULTS)
    )

Most frequent values for OP_UNIQUE_CARRIER:

DataFrame[OP_UNIQUE_CARRIER: string, count: bigint]

Most frequent values for ORIGIN:

DataFrame[ORIGIN: string, count: bigint]

Most frequent values for DEST:

DataFrame[DEST: string, count: bigint]

Most frequent values for CANCELLATION_CODE:

DataFrame[CANCELLATION_CODE: string, count: bigint]

#### Essential data-quality checks

This section verifies the valid ranges and values of the main operational variables.

In [12]:
# Perform essential range and binary-value checks

quality_checks = [
    (
        "Invalid QUARTER values",
        df_raw.filter(
            F.col(cfg.QUARTER_COLUMN).isNull()
            | ~F.col(cfg.QUARTER_COLUMN).between(1, 4)
        ).count(),
    ),
    (
        "Invalid MONTH values",
        df_raw.filter(
            F.col(cfg.MONTH_COLUMN).isNull()
            | ~F.col(cfg.MONTH_COLUMN).between(1, 12)
        ).count(),
    ),
    (
        "Invalid DAY_OF_WEEK values",
        df_raw.filter(
            F.col(cfg.DAY_OF_WEEK_COLUMN).isNull()
            | ~F.col(cfg.DAY_OF_WEEK_COLUMN).between(1, 7)
        ).count(),
    ),
    (
        "Invalid CANCELLED values",
        df_raw.filter(
            F.col(cfg.CANCELLED_COLUMN).isNull()
            | ~F.col(cfg.CANCELLED_COLUMN).isin(0, 1)
        ).count(),
    ),
    (
        "Invalid DIVERTED values",
        df_raw.filter(
            F.col(cfg.DIVERTED_COLUMN).isNull()
            | ~F.col(cfg.DIVERTED_COLUMN).isin(0, 1)
        ).count(),
    ),
    (
        "Invalid ARR_DEL15 values",
        df_raw.filter(
            F.col(cfg.ARRIVAL_DELAY_FLAG_COLUMN).isNotNull()
            & ~F.col(
                cfg.ARRIVAL_DELAY_FLAG_COLUMN
            ).isin(0, 1)
        ).count(),
    ),
    (
        "Invalid DEP_DEL15 values",
        df_raw.filter(
            F.col(cfg.DEPARTURE_DELAY_FLAG_COLUMN).isNotNull()
            & ~F.col(
                cfg.DEPARTURE_DELAY_FLAG_COLUMN
            ).isin(0, 1)
        ).count(),
    ),
    (
        "Non-positive DISTANCE values",
        df_raw.filter(
            F.col(cfg.DISTANCE_COLUMN).isNull()
            | (F.col(cfg.DISTANCE_COLUMN) <= 0)
        ).count(),
    ),
    (
        "Non-positive CRS_ELAPSED_TIME values",
        df_raw.filter(
            F.col(cfg.SCHEDULED_ELAPSED_TIME_COLUMN).isNull()
            | (F.col(cfg.SCHEDULED_ELAPSED_TIME_COLUMN) <= 0)
        ).count(),
    ),
    (
        "Non-positive ACTUAL_ELAPSED_TIME values",
        df_raw.filter(
            F.col(cfg.ACTUAL_ELAPSED_TIME_COLUMN).isNotNull()
            & (F.col(cfg.ACTUAL_ELAPSED_TIME_COLUMN) <= 0)
        ).count(),
    ),
    (
        "Non-positive AIR_TIME values",
        df_raw.filter(
            F.col(cfg.AIR_TIME_COLUMN).isNotNull()
            & (F.col(cfg.AIR_TIME_COLUMN) <= 0)
        ).count(),
    ),
    (
        "Negative TAXI_OUT values",
        df_raw.filter(
            F.col(cfg.TAXI_OUT_COLUMN).isNotNull()
            & (F.col(cfg.TAXI_OUT_COLUMN) < 0)
        ).count(),
    ),
    (
        "Negative TAXI_IN values",
        df_raw.filter(
            F.col(cfg.TAXI_IN_COLUMN).isNotNull()
            & (F.col(cfg.TAXI_IN_COLUMN) < 0)
        ).count(),
    ),
]

# Extend with a negative-value check for each delay-cause column
# (null is tolerated: delay-cause columns are only populated when a delay occurred)

quality_checks.extend(
    [
        (
            f"Negative {column_name} values",
            df_raw.filter(
                F.col(column_name).isNotNull()
                & (F.col(column_name) < 0)
            ).count(),
        )
        for column_name in cfg.DELAY_CAUSE_COLUMNS
    ]
)

quality_checks_df = spark.createDataFrame(
    quality_checks,
    [
        "quality_check",
        "invalid_record_count",
    ],
)

display(quality_checks_df)

DataFrame[quality_check: string, invalid_record_count: bigint]

#### Dataset preview

A small sample is displayed to support a final visual review of the raw records.

In [13]:
display(df_raw.limit(10))

DataFrame[QUARTER: int, MONTH: int, DAY_OF_WEEK: int, FL_DATE: string, OP_UNIQUE_CARRIER: string, OP_CARRIER_FL_NUM: int, ORIGIN: string, ORIGIN_CITY_NAME: string, ORIGIN_STATE_NM: string, DEST: string, DEST_CITY_NAME: string, DEST_STATE_NM: string, CRS_DEP_TIME: int, DEP_DELAY: double, DEP_DEL15: double, TAXI_OUT: double, TAXI_IN: double, CRS_ARR_TIME: int, ARR_DELAY: double, ARR_DEL15: double, CANCELLED: double, CANCELLATION_CODE: string, DIVERTED: double, CRS_ELAPSED_TIME: double, ACTUAL_ELAPSED_TIME: double, AIR_TIME: double, DISTANCE: double, CARRIER_DELAY: double, WEATHER_DELAY: double, NAS_DELAY: double, SECURITY_DELAY: double, LATE_AIRCRAFT_DELAY: double]

#### Profiling completion

In [14]:
print("Data profiling completed successfully.")

Data profiling completed successfully.